seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  gradient_clip_val: 1.0
  max_steps: 1
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: null
      save_dir: null

model:
  model_name: kaiyuy/leandojo-lean4-retriever-byt5-small
  lr: 0
  warmup_steps: 0
  num_retrieved: 1

data:
  data_path: data/leandojo_benchmark_4/random/
  corpus_path: data/leandojo_benchmark_4/corpus.jsonl
  num_negatives: 1
  num_in_file_negatives: 0
  batch_size: 1
  eval_batch_size: 64
  max_seq_len: 256
  num_workers: 4
  prefetch_factor: 2
