seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  strategy:
    class_path: pytorch_lightning.strategies.DeepSpeedStrategy
    init_args:
      stage: 2
      offload_optimizer: false
      cpu_checkpointing: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: predict_retriever_val100_augmented
      save_dir: out/predict_retriever_val100_augmented
  gradient_clip_val: 1.0
  max_steps: 800000
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: Recall@10_val
        mode: max
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: Recall@10_val
        patience: 5
        mode: max
        verbose: true

ckpt_path: out/train_retriever_random/lightning_logs/ywq35zh8/checkpoints/epoch=0-step=1.ckpt

model:
  model_name: kaiyuy/leandojo-lean4-retriever-byt5-small
  lr: 1e-4
  warmup_steps: 2000
  num_retrieved: 100

data:
  data_path: data/leandojo_benchmark_4/random/
  corpus_path: data/leandojo_benchmark_4/corpus.jsonl
  pred_ds: data/leandojo_benchmark_4/random/val_100.json
  indexed_corpus_path: out/train_retriever_random/index.pkl
  custom_queries_path: data/leandojo_benchmark_4/random/val100_gp5_raw.jsonl
  num_negatives: 1
  num_in_file_negatives: 0
  batch_size: 1
  eval_batch_size: 64
  max_seq_len: 1024
  num_workers: 4
  prefetch_factor: 2
